export const EDUCATION_UPDATE_HEADER = 'EDUCATION_UPDATE_HEADER'
export const EDUCATION_UPDATE_SCHOOL = 'EDUCATION_UPDATE_SCHOOL'
export const EDUCATION_UPDATE_COURSE = 'EDUCATION_UPDATE_COURSE'
export const EDUCATION_UPDATE_TITLE = 'EDUCATION_UPDATE_TITLE'
export const EDUCATION_UPDATE_CITY = 'EDUCATION_UPDATE_CITY'
export const EDUCATION_UPDATE_COUNTRY = 'EDUCATION_UPDATE_COUNTRY'
export const EDUCATION_UPDATE_FROM_DATE = 'EDUCATION_UPDATE_FROM'
export const EDUCATION_UPDATE_TO_DATE = 'EDUCATION_UPDATE_TO'
export const EDUCATION_UPDATE_DESCRIPTION = 'EDUCATION_UPDATE_DESCRIPTION'
export const EDUCATION_DELETE_EDUCATION = 'EDUCATION_DELETE_EDUCATION'
export const EDUCATION_ADD_EDUCATION = 'EDUCATION_ADD_EDUCATION'


