export const SKILLS_UPDATE_HEADER = 'SKILLS_UPDATE_HEADER'
export const SKILLS_UPDATE_SKILL = 'SKILLS_UPDATE_SKILL'
export const SKILLS_ADD_SKILL = 'SKILLS_ADD_SKILL'
export const SKILLS_DELETE_SKILL = 'SKILLS_DELETE_SKILL'


