export const EXPERIENCE_UPDATE_HEADER = 'EXPERIENCE_UPDATE_HEADER'
export const EXPERIENCE_UPDATE_POSITION = 'EXPERIENCE_UPDATE_POSITION'
export const EXPERIENCE_UPDATE_COMPANY = 'EXPERIENCE_UPDATE_COMPANY'
export const EXPERIENCE_UPDATE_CITY = 'EXPERIENCE_UPDATE_CITY'
export const EXPERIENCE_UPDATE_COUNTRY = 'EXPERIENCE_UPDATE_COUNTRY'
export const EXPERIENCE_UPDATE_FROM_DATE = 'EXPERIENCE_UPDATE_FROM_DATE'
export const EXPERIENCE_UPDATE_TO_DATE = 'EXPERIENCE_UPDATE_TO_DATE'
export const EXPERIENCE_UPDATE_DESCRIPTION = 'EXPERIENCE_UPDATE_DESCRIPTION'
export const EXPERIENCE_DELETE_EXPERIENCE = 'EXPERIENCE_DELETE_EXPERIENCE'
export const EXPERIENCE_ADD_EXPERIENCE = 'EXPERIENCE_ADD_EXPERIENCE'


