export const HOBBIES_UPDATE_HEADER = 'HOBBIES_UPDATE_HEADER'
export const HOBBIES_UPDATE_HOBBY = 'HOBBIES_UPDATE_HOBBY'
export const HOBBIES_ADD_HOBBY = 'HOBBIES_ADD_HOBBY'
export const HOBBIES_DELETE_HOBBY = 'HOBBIES_DELETE_HOBBY'


