export const PROJECTS_UPDATE_HEADER = 'PROJECTS_UPDATE_HEADER'
export const PROJECTS_UPDATE_PROJECT = 'PROJECTS_UPDATE_PROJECT'
export const PROJECTS_UPDATE_COMPANY = 'PROJECTS_UPDATE_COMPANY'
export const PROJECTS_UPDATE_CITY = 'PROJECTS_UPDATE_CITY'
export const PROJECTS_UPDATE_COUNTRY = 'PROJECTS_UPDATE_COUNTRY'
export const PROJECTS_UPDATE_POSITION = 'PROJECTS_UPDATE_POSITION'
export const PROJECTS_UPDATE_FROM_DATE = 'PROJECTS_UPDATE_FROM_DATE'
export const PROJECTS_UPDATE_TO_DATE = 'PROJECTS_UPDATE_TO_DATE'
export const PROJECTS_UPDATE_DESCRIPTION = 'PROJECTS_UPDATE_DESCRIPTION'
export const PROJECTS_DELETE_PROJECT = 'PROJECTS_DELETE_PROJECT'
export const PROJECTS_ADD_PROJECT = 'PROJECTS_ADD_PROJECT'


