export const UPDATE_FIRST_NAME = 'UPDATE_HEADER_CONTENTS'
export const UPDATE_SECOND_NAME = 'UPDATE_SECOND_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_POSITION = 'UPDATE_POSITION'
