export const EDUCATION_UPDATE_HEADER = 'EDUCATION_UPDATE_HEADER'
export const EDUCATION_UPDATE_SCHOOL = 'EDUCATION_UPDATE_SCHOOL'
export const EDUCATION_UPDATE_TITLE = 'EDUCATION_UPDATE_TITLE'
export const EDUCATION_UPDATE_CITY = 'EDUCATION_UPDATE_CITY'
export const EDUCATION_UPDATE_COUNTRY = 'EDUCATION_UPDATE_COUNTRY'
export const EDUCATION_UPDATE_FROM = 'EDUCATION_UPDATE_FROM'
export const EDUCATION_UPDATE_TO = 'EDUCATION_UPDATE_TO'
export const EDUCATION_UPDATE_DESCRIPTION = 'EDUCATION_UPDATE_DESCRIPTION'
export const EXPERIENCE_DELETE_EXPERIENCE = 'EXPERIENCE_DELETE_EXPERIENCE'
export const EXPERIENCE_ADD_EXPERIENCE = 'EXPERIENCE_ADD_EXPERIENCE'


