export const LINKS_UPDATE_HEADER = 'LINKS_UPDATE_HEADER'
export const LINKS_UPDATE_LINK = 'LINKS_UPDATE_LINK'
export const LINKS_ADD_LINK = 'LINKS_ADD_LINK'
export const LINKS_DELETE_LINK = 'LINKS_DELETE_LINK'


