export const CERTIFICATES_UPDATE_HEADER = 'CERTIFICATES_UPDATE_HEADER'
export const CERTIFICATES_UPDATE_CERTIFICATE = 'CERTIFICATES_UPDATE_CERTIFICATE'
export const CERTIFICATES_UPDATE_ISSUER = 'CERTIFICATES_UPDATE_ISSUER'
export const CERTIFICATES_UPDATE_VALID_UNTIL = 'CERTIFICATES_UPDATE_VALID_UNTIL'
export const CERTIFICATES_DELETE_CERTIFICATE = 'CERTIFICATES_DELETE_CERTIFICATE'
export const CERTIFICATES_ADD_CERTIFICATE = 'CERTIFICATES_ADD_CERTIFICATE'


